### ISSUE TITLE
Using Swagger with ASYNC 

### ISSUE THREAD

**Issue by aogaki** [oatpp/oatpp-swagger#6]
I am trying to use swagger on oatpp/example-crud.  First, I modified controller and it works well.  The next, I tried to use #include "oatpp-swagger/AsyncController.hpp" in App.cpp.  And I got 

/usr/local/include/oatpp-0.19.1/oatpp-swagger/oatpp-swagger/AsyncController.hpp:32:10: fatal error: oatpp/web/server/HttpError.hpp: No such file or directory

I tried to find HttpError.hpp, but I could not find it.  Do you have any idea about it?
Best,

**Comment by lganzzzo** [comment]
Hello @aogaki ,

Thank you for the issue report, and sorry for the late response.

This issue has been fixed in the latest commit https://github.com/oatpp/oatpp-swagger/commit/2c4deb3f3adfe9e2cc5932deaf3bd8dbadfe29f3 .

Also I created an example project for you - how to document async APIs - https://github.com/lganzzzo/oatpp-swagger-with-async-api

Please let me know if you need additional help.

Best Regards,
Leonid

**Comment by aogaki** [comment]
Hello @lganzzzo ,
Thank you so much for your work.
